### ISSUE TITLE
Bound Boxes Coordinates

### ISSUE THREAD

**Issue by tassomoraes** [keiserlab/plaquebox-paper#3]
Hi, I'm trying to use the alzhaimer dataset in a explicability metric study and I'd like  to know if could you provide de bound boxes coordinate of the tiles images.

Thank you.

**Comment by mjke** [comment]
for these data, please access the zenodo data repo that accompanies the paper, at: [Data for: Tang et al., Interpretable classification of Alzheimer's disease ... DOI 10.5281/zenodo.1470797](https://zenodo.org/record/1470797)
